### ISSUE TITLE
FROM container-registry.oracle.com/os/oraclelinux:8.6 failing on MacOS 14.6 but working on Ubuntu

### ISSUE THREAD

**Issue by fleetfootmike** [oracle/container-images#106]
```
...
2.210 Oracle Linux 8 BaseOS Latest (aarch64)           69 MB/s | 117 MB     00:01    
15.01 Oracle Linux 8 Application Stream (aarch64)     2.6 MB/s | 3.9 MB     00:01    
15.01 Errors during downloading metadata for repository 'ol8_appstream':
15.01   - Curl error (18): Transferred a partial file for https://yum.oracle.com/repo/OracleLinux/OL8/appstream/aarch64/repodata/80ae3a0b30b981468b86fa454ede8b6d61e98b5f6e47c634bbc4a376e89df504-primary.xml.gz [transfer closed with 6071352 bytes remaining to read]
...
```
ditto for other files.

**Comment by amsteinb-orcl** [comment]
That looks like a network issue, not related to the container image.

**Comment by tvierling** [comment]
If this issue is still a problem, please reopen, but this looks like there was an issue with the mirror you were using at the time (probably corrected by now).

Also please do not use images like `.../oraclelinux:8.6`. That is out of date by definition because it is not at the latest patchlevel. Please use only `.../oraclelinux:8` with a single number (the product version is OL8, not OL8.6 — the .6 is a patchlevel).

**Comment by fleetfootmike** [comment]
Still failing as above on MacOS, still fine on Ubuntu.

Not managed to prove it's an issue local to me, though.

**Comment by fleetfootmike** [comment]
It does.
