### ISSUE TITLE
Add difference between slim and non-slim images to readme.

### ISSUE THREAD

**Issue by milosonator** [oracle/container-images#13]
Currently it is not clear from the readme what the difference is between the slim and non-slim images. When should either be used? What does the slim image lack that the normal image has?

**Comment by Djelibeybi** [comment]
This is a fair assessment and I'll update the README in the next couple of days. 

In the interim and for your knowledge, the slim image contains just enough of user space to run `yum` in order to install what you _actually_ need. The non-slim image matches an `@base` install of Oracle Linux via kickstart.

**Comment by Djelibeybi** [comment]
I still need to do this, but I'm closing it for now and will revisit later. The upstream official image has this information.
