### ISSUE TITLE
Slim builds should include their base version

### ISSUE THREAD

**Issue by colt3k** [oracle/container-images#23]
Full builds have 6.10 etc... but slim builds don't include a full version number, should we just assume they're the latest of the whole version?

**Comment by Djelibeybi** [comment]
Yes. The tags with just the version number (and no update level) are recommended because they are kept up-to-date automatically by Oracle. We strongly recommend NOT using a specific update level, i.e. `6.10`. You should use `oraclelinux:6` or `oraclelinux:6-slim`. That's the only way to guarantee you're using a base image that is being updated.

This is because once a new update level is released, older update levels stop receiving updates.
