### ISSUE TITLE
please build oraclelinux:8 without /dev/initctl so it can be pulled to nfs/diskless clients

### ISSUE THREAD

**Issue by sneely333** [oracle/container-images#77]
NFS 4.2 along with a kernel > 5.9 allows for podman being able to pull images into a nfs mounted directory.  This is due to the s
upport for extended attributes  being added to nfs (https://datatracker.ietf.org/doc/rfc8276/)

Unfortunately support for getxattr, setxattr and listxattr was added but not support for lsetxattr (ie. setxattr -h).  The oracle
linux:8 image contains the link /dev/initctl with extended attributes which comes from oraclelinux-8-amd64-rootfs.tar.xz. Althoug
h this link is removed when a container is run, because it is in the base image, we cannot use podman on nfs mounted home directo
ries as it fails to load the image.

If I download oraclelinux-8-amd64-rootfs.tar.xz from GitHub along with the Dockerfile, I can remove /dev/initctl from oraclelinux
-8-amd64-rootfs.tar.xz and rebuild the image locally it works great.  Is there any way to get this change into the base image as
this file does not appear necessary?

Or please let me know if there is a better solution.

**Comment by tvierling** [comment]
This will not be changed in the base image because generally we do not support use of Podman with NFS container paths (not the least because SELinux will not work properly with many NFS servers). We strongly recommend configuring the Podman storage configuration to keep your container root filesystems on local filesystems.

If you need this hack, you will need to rebuild the image.
